# This file contains values from Cookiecutter

default_context:
  project_name: "cfpi"
  project_description: "Offline Reinforcement Learning with Closed-Form Policy Improvement Operators"
  organization: "ezhang7423"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "ezhang7423"
  email: "ete@ucsb.edu"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
